// =================================================================
// Module: accumulator_1ms
// Description: Accumulates a 4-bit signed input on every clock edge.
//              Unlike the previous version, this module does NOT
//              count clock ticks itself -- instead, an external
//              "ms_interrupt" pulse (generated by the testbench, or
//              in real hardware by a separate timer block) tells
//              the module when 1ms has elapsed.
//
//              On the clock edge where ms_interrupt = 1:
//                - the current sample (data_in) is folded into the
//                  running total one last time
//                - that total is latched out to ACCUMDATA
//                - the internal accumulator resets to 0, ready for
//                  the next 1ms window
//
//              Within 1ms (16368 ticks), the 16-bit signed
//              accumulator will NOT overflow for realistic
//              (oscillating, noise-like) input data. Fixed
//              worst-case values (like a constant +3) are used
//              separately just to verify the wrap-around behaviour
//              at the edge of the design's range.
// =================================================================
module accumulator_1ms (
    input  wire              clk,          // system clock
    input  wire              reset,        // synchronous reset
    input  wire signed [3:0] data_in,      // 4-bit signed sample, new value every tick
    input  wire              ms_interrupt, // pulse from testbench: 1 = this is the last tick of the 1ms window
    output reg  signed [15:0] ACCUMDATA    // 16-bit signed accumulated total, latched every 1ms
);

    reg signed [15:0] acc;   // running total for the current 1ms window

    always @(posedge clk) begin
        if (reset) begin
            acc       <= 16'sd0;
            ACCUMDATA <= 16'sd0;
        end else if (ms_interrupt) begin
            // last tick of this window: fold in this sample, latch, and reset
            ACCUMDATA <= acc + data_in;   // wraps automatically if it overflows 16 bits
            acc       <= 16'sd0;
        end else begin
            acc <= acc + data_in;
        end
    end

endmodule
